version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  neo4j:
    image: neo4j:4.4
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - '8474:7474'
      - '8687:7687'
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpassword", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  migration:
    build: ./migration
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      neo4j:
        condition: service_healthy

volumes:
  mysql_data:
  mongo_data:
  neo4j_data:
